version: '2'
services:
  worker:
    privileged: true
    image: supersoftware/rancher-spark:latest
    environment:
      MASTER_HOSTNAME: master
      affinity:container!: /worker/
      constraint:node!: /node0/
    command:
    - worker
  master:
    privileged: true
    image: supersoftware/rancher-spark:latest
    hostname: master
    environment:
      constraint:node: =/node0/
    command:
    - master
